### ISSUE TITLE
bug or not in the "aus_clade_size.R" file?

### ISSUE THREAD

**Issue by liamxg** [LeoFeatherstone/helicoBycatch#7]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/46078579/231722901-2127add9-0ef6-441d-837d-22e75f72c8b9.png">

**Comment by liamxg** [comment]
@LeoFeatherstone

**Comment by LeoFeatherstone** [comment]
Hi @liamxg,

Apologies, these analyses of posterior clade size were never included in the manuscript and the `.trees` files were never uploaded, so this would indeed be a bug on the user end. I have removed the `aus_clade_size.R` script and it utilities `get_clades.R` because these are unnecessary to reproduce the results of the manuscript. Thank you for raising this.

Kind regards,
Leo

**Comment by liamxg** [comment]
@LeoFeatherstone thanks, but this is a mazing script to me.
